export const GET_ERRORS = '[ERROR] GET_ERRORS';
export const CLEAR_ERRORS = '[ERROR] CLEAR_ERRORS';

export const SET_CURRENT_USER = '[INIT] SET_CURRENT_USER';
export const SET_REGISTERED_USER = '[ADMIN] SET_REGISTERED_USER';

export const CHANGE_PASSWORD = '[AUTH] CHAGE_PASSWORD';

export const GET_PROFILE = '[PROFILE] GET_PROFILE';
export const PROFILE_LOADING = '[PROFILE] PROFILE_LOADING';
export const PROFILE_NOT_FOUND = '[PROFILE] PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = '[PROFILE] CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = '[PROFILE] GET_PROFILES';
export const EDIT_PROFILE = '[PROFILE] EDIT_PROFILE';
export const GET_TARGET_PROFILE = '[PROFILE] GET_TARGET_PROFILE';

export const TASK_LOADING = '[TASK] TASK_LOADING';
export const GET_TASKS = '[TASK] GET_TASKS';
export const GET_TASK = '[TASK] GET_TASK';
export const ADD_TASK = '[TASK] ADD_TASK';
export const DELETE_TASK = '[TASK] DELETE_TASK';
export const ADD_SUB_TASK = '[TASK] ADD_SUB_TASK';
export const REPLY_TO_THREAD = '[TASK] REPLY_TO_THREAD';

export const GET_SKILLS = '[SKILL] GET_SKILLS';
export const GET_SKILL = '[SKILL] GET_SKILL';

export const TEAM_LOADING = "[TEAM] TEAM_LOADING";
export const GET_TEAMS = "[TEAM] GET_TEAMS";
export const GET_TEAM = "[TEAM] GET_TEAM";
export const ADD_TEAM = "[TEAM] ADD_TEAM";

export const GET_SQUADRONS = "[ORGANIZATION] GET_SQUADRONS";

export const CONNECTION_ESTABLISHED = "[SOCKET] CONNECTION_ESTABLISHED"